apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp
#    type: front-end or fronted
#    costcenter: amer
#    location : NA

spec:
  containers: # array or list
    - name: nginx-container
      image: nginx
#  nodeSelector:
#    size: Large
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key : size
            operator: In
            value:
            - Large
#    - name: backend-container
#      image: redis
