openssl genrsa -out jane.key 2048
openssl req -new -key jane.key -subj "/CN=jane" -out jane.csr

apiVersion: certificates.k8s.io/v1beta1
kind: CertificatesSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:

(cat jane.csr | base 64) copy



kubectl get csr
kubectl certificate approve jane
