apiVersion: certificates.k8s.io/v1beta1
kind: CertificatesSigningRequest
metadata:
  name: jane
spec:
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:

(cat jane.csr | base 64) copy
