apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://kube-apivserver:6443
  name: kubernetes
kind: Config
users:
- name: kubernetes-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key
