apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-100 -n 1 >> /pot/number.out;"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume # in Pod

  volumes:
  - name: data-volume # in lab
    hostPath:
      path: /data
      type: Directory

or

  volumes:
  - name: data-volume
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4
