apiVersion: v1
kind: Pod
metadata:
  name: simeple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
    - containerPort: 8080

    envFrom:
    - configMapRef
        name: app-config

      #    env:
      # - name: APP_COLOR
      #   value: blue
      # - name: APP_MODE
      #  value: prod
      #
      #
      #
      #  kubectl create configmap app-config --from-literal=APP_COLOR=blue
      #  kubectl create configmap app-config --from-file=app_config.properties
