#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: ssa

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scr
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: scrb
subjects:
- kind: User
  name: system:serviceaccount:kube-system:default
  namespace: default
roleRef:
  kind: ClusterRole
  name: scr
  apiGroup: rbac.authorization.k8s.io

