apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod1
  #namespace: dev
  labels:
    app: myapp
#    type: front-end or fronted
#    costcenter: amer
#    location : NA

spec:
  containers: # array or list
    - name: nginx-container
      image: nginx

#    - name: backend-container
#      image: redis
  nodeName: node02
