apiVersion: v1
kind: Binding
metadata:
  name: myapp-pod1
target:
  apiVersion: v1
  kind: Node
  name: ck-gpu1


then
curl --header "Contect-Type:applicatoin/json" --request POST --data '{"apiVersion":"v1", "kind": "Binding" ... }' http://$SERVER/api/v1/namespaces/default/pods/$PODNAME/binding/
