apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
#    type: front-end

spec:
  template:
    metadata:
      name: myapp
      labels:
        A: B
    spec:
      containers:
      - name: nginx-container
        image: nginx

  replicas: 3
  selector: 
    matchLabels:
      A: B
