apiVersion: v1
kind: Pod

metadata:
        name: myapp-pod1
        labels:
                app: myapp
                type: front-end

spec:
        containers:
        - name: nginx-container
          image: nginx
