apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx # docker.io(registry, docker hub)/nginx(user account)/nginx

gcr.io/kubernetes-e2e-test-images/dnsutils # google registry, dnsutils: kuberntes related images


first login
docker login private-registory.io
docker run private-registry.io/apps/internal-app


make secret
kubectl create secret docker-registry regcred \
--docker-server=private-registry.io \
--docker-username=registry-user \
--docker-password=registry-password \
--docker-email=registry-user@org.com


add
spec:
  containers:
  ~~
  imagePullSecrets:
  - name: regcred
