apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
- apiGroups: [""] # core group is blank.
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]
  resoureNames: ["blue", "orange"] # pod name


# if you want, use namespace, this is default namespace

#kubectl api-resources --namespaced=true/false
