apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
  labels:
    for: private
spec:
  containers:
  - name: ubuntu-sleeper
    image: 172.17.0.2:5000/ubuntu-sleeper
    args: ["10"]
    #imagePullPolicy: Never
    #command: ["sleep"]
