apiVersion: v1
kind: Service
metadata:
        name: forprivate

spec:
        type: NodePort
        ports:
        - targetPort: 8080
          port: 80
          nodePort: 30018
        selector:
                for: private
